[project]
name = "ml-algo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "intel-tensorflow>=0.0.1",
    "matplotlib>=3.10.3",
    "numpy>=2.1.3",
    "tensorflow>=2.19.0",
    "tensorflow-intel>=0.0.1",
]
